# Generated by Django 4.1.5 on 2023-01-11 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shots', '0002_judge_session_name_session_status_session_judges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='judges',
        ),
        migrations.AddField(
            model_name='session',
            name='judges',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
