# Generated by Django 3.2.13 on 2023-01-17 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shots', '0003_remove_session_judges_session_judges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='judges',
        ),
        migrations.AddField(
            model_name='session',
            name='judges',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
