# Generated by Django 4.1.7 on 2023-02-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0004_auto_20230117_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(default='lobby', max_length=255),
        ),
    ]
