# Generated by Django 4.1.7 on 2023-03-06 13:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0005_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='eliminations_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1], size=None),
        ),
        migrations.AddField(
            model_name='player',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shots.judge'),
        ),
    ]
