# Generated by Django 4.1.7 on 2023-03-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shots', '0005_alter_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='eliminations_score',
            field=models.CharField(default='-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shots.judge'),
        ),
    ]
